name = "freedirect-worker"
main = "worker.js"           # <-- your Worker script file
compatibility_date = "2025-10-30"
type = "javascript"          # or "webpack" / "modules" if using modules

# Optional: KV namespace binding
kv_namespaces = [
  { binding = "FD_Storage", id = "f76a5e6aac6f4d9e9895f01386b78473" }
]
